[project]
name = "site-audit-ai-be"
version = "0.1.0"
description = "Sitelytics Backend Service"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "annotated-doc==0.0.4",
    "annotated-types==0.7.0",
    "anyio==4.11.0",
    "click==8.3.1",
    "fastapi==0.121.2",
    "greenlet==3.2.4",
    "h11==0.16.0",
    "idna==3.11",
    "psycopg[binary]>=3.2.12",
    "pydantic[email]==2.12.4",
    "pydantic-core==2.41.5",
    "python-dotenv==1.2.1",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.44",
    "starlette==0.49.3",
    "typing-extensions==4.15.0",
    "typing-inspection==0.4.2",
    "uvicorn==0.38.0",
    "alembic>=1.17.2",
    "python-jose[cryptography]>=3.5.0",
    "google-auth>=2.43.0",
    "google-auth-oauthlib>=1.2.2",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.1",
]

# ------------------------
# RUFF CONFIG
# ------------------------
[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = [
  "E",
  "F",
  "I",
  "B",
  "UP",
]
ignore = [
  "E501",
  "B008"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
]
